### ISSUE TITLE
Hey! tsyuay how about putting this image on the friv panel on the display in this repository, I created it. I would be happy if you accepted my proposal!

### ISSUE THREAD

**Issue by HardPowerhtml** [Tsyuay/Tsyuay.github.io#1]
![friv](https://github.com/Tsyuay/Tsyuay.github.io/assets/139723797/7c28fe20-4558-4f8a-8bb0-0f4524f3c16c)
![frivheroes](https://github.com/Tsyuay/Tsyuay.github.io/assets/139723797/d12001e2-663f-4ae6-9999-a430d317e2c2)

**Comment by Tsyuay** [comment]
Sorry for the late response, but I think it's a good idea, I'll later put this image
